config/routes.rb
Rails.application.routes.draw do
  resources :queries

  devise_for :users, :controllers => { registrations: 'registrations' }

  get 'estadisticas/index'

  resources :movimientos

  resources :formapagos

  resources :tipomovs

  resources :tipogastos

  resources :subrubros

  resources :rubros

  root to: 'queries#index'

end

app/models/tipogasto.rb
class Tipogasto < ActiveRecord::Base
end

app/controllers/tipogastos_controller.rb
class TipogastosController < ApplicationController
  before_action :set_tipogasto, only: [:show, :edit, :update, :destroy]

  # GET /tipogastos
  # GET /tipogastos.json
  def index
    @tipogastos = Tipogasto.all
  end

  # GET /tipogastos/1
  # GET /tipogastos/1.json
  def show
  end

  # GET /tipogastos/new
  def new
    @tipogasto = Tipogasto.new
  end

  # GET /tipogastos/1/edit
  def edit
  end

  # POST /tipogastos
  # POST /tipogastos.json
  def create
    @tipogasto = Tipogasto.new(tipogasto_params)

    respond_to do |format|
      if @tipogasto.save
        format.html { redirect_to @tipogasto, notice: 'Se creo correctamente el Tipo de gasto.' }
        format.json { render :show, status: :created, location: @tipogasto }
      else
        format.html { render :new }
        format.json { render json: @tipogasto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipogastos/1
  # PATCH/PUT /tipogastos/1.json
  def update
    respond_to do |format|
      if @tipogasto.update(tipogasto_params)
        format.html { redirect_to @tipogasto, notice: 'Se actualizo correctamente el Tipo de gasto.' }
        format.json { render :show, status: :ok, location: @tipogasto }
      else
        format.html { render :edit }
        format.json { render json: @tipogasto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipogastos/1
  # DELETE /tipogastos/1.json
  def destroy
    @tipogasto.destroy
    respond_to do |format|
      format.html { redirect_to tipogastos_url, notice: 'Se borro correctamente el Tipo de gasto.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipogasto
      @tipogasto = Tipogasto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipogasto_params
      params.require(:tipogasto).permit(:tga_desc)
    end
end

app/helpers/tipogastos_helper.rb
module TipogastosHelper
end

app/views/tipogastos/_form.html.erb
<%= form_for(@tipogasto) do |f| %>
  <% if @tipogasto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipogasto.errors.count, "error") %> prohibited this tipogasto from being saved:</h2>

      <ul>
      <% @tipogasto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tga_desc %><br>
    <%= f.text_field :tga_desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipogastos/edit.html.erb
<h1>Editing tipogasto</h1>

<%= render 'form' %>

<%= link_to 'Show', @tipogasto %> |
<%= link_to 'Back', tipogastos_path %>

app/views/tipogastos/index.html.erb
<h1>Listing tipogastos</h1>

<table>
  <thead>
    <tr>
      <th>Tga desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipogastos.each do |tipogasto| %>
      <tr>
        <td><%= tipogasto.tga_desc %></td>
        <td><%= link_to 'Show', tipogasto %></td>
        <td><%= link_to 'Edit', edit_tipogasto_path(tipogasto) %></td>
        <td><%= link_to 'Destroy', tipogasto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tipogasto', new_tipogasto_path %>

app/views/tipogastos/new.html.erb
<h1>New tipogasto</h1>

<%= render 'form' %>

<%= link_to 'Back', tipogastos_path %>

app/views/tipogastos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tga desc:</strong>
  <%= @tipogasto.tga_desc %>
</p>

<%= link_to 'Edit', edit_tipogasto_path(@tipogasto) %> |
<%= link_to 'Back', tipogastos_path %>