config/routes.rb
Rails.application.routes.draw do
  resources :queries

  devise_for :users, :controllers => { registrations: 'registrations' }

  get 'estadisticas/index'

  resources :movimientos

  resources :formapagos

  resources :tipomovs

  resources :tipogastos

  resources :subrubros

  resources :rubros

  root to: 'queries#index'

end

app/models/rubro.rb
class Rubro < ActiveRecord::Base
end

app/controllers/rubros_controller.rb
class RubrosController < ApplicationController
  before_action :set_rubro, only: [:show, :edit, :update, :destroy]

  # GET /rubros
  # GET /rubros.json
  def index
    @rubros = Rubro.all
  end

  # GET /rubros/1
  # GET /rubros/1.json
  def show
  end

  # GET /rubros/new
  def new
    @rubro = Rubro.new
  end

  # GET /rubros/1/edit
  def edit
  end

  # POST /rubros
  # POST /rubros.json
  def create
    @rubro = Rubro.new(rubro_params)

    respond_to do |format|
      if @rubro.save
        format.html { redirect_to @rubro, notice: 'Se creo correctamente el Rubro.' }
        format.json { render :show, status: :created, location: @rubro }
      else
        format.html { render :new }
        format.json { render json: @rubro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rubros/1
  # PATCH/PUT /rubros/1.json
  def update
    respond_to do |format|
      if @rubro.update(rubro_params)
        format.html { redirect_to @rubro, notice: 'Se actualizo correctamente el Rubro.' }
        format.json { render :show, status: :ok, location: @rubro }
      else
        format.html { render :edit }
        format.json { render json: @rubro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rubros/1
  # DELETE /rubros/1.json
  def destroy
    @rubro.destroy
    respond_to do |format|
      format.html { redirect_to rubros_url, notice: 'Se borro correctamente el Rubro.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rubro
      @rubro = Rubro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rubro_params
      params.require(:rubro).permit(:rub_desc, :rub_suma)
    end
end

app/helpers/rubros_helper.rb
module RubrosHelper
end

app/views/rubros/_form.html.erb
<%= form_for(@rubro, html: {class: "form-horizontal"}) do |f| %>
  <% if @rubro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rubro.errors.count, "error") %> prohibited this rubro from being saved:</h2>

      <ul>
      <% @rubro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <form class="form-inline" role="form">

    <div id="form-new" class="form-group has-success has-feedback">
      <%= f.text_field :rub_desc, :placeholder => "Ingrese la descripcion del Rubro...", :class=>"form-control", autofocus: true %>
    </div>

    <div id="form-new" class="form-group has-success has-feedback">
      <%= f.label "El rubro suma?" %>
      <%= f.check_box :rub_suma, :id=>"campo-checkbox", :class=>"form-control" %>
    </div>

    <div class="actions">
      <%= f.submit "Confirmar", :class => "btn btn-primary" %>
      <%= link_to 'Ir Atras', rubros_path, class: "btn btn-primary" %>
      <%- if @vMostrarBorrar %>
      <%= link_to 'Borrar', @rubro, method: :delete, data: { confirm: 'Esta seguro que desea borrar este rubro?' }, :id => "boton-borrar", :class => "btn btn-primary" %>
      <% end -%>
    </div>

  </form>

<% end %>

app/views/rubros/edit.html.erb
<div class="page-header">
  <h3><u>Modificar Rubro</u></h3>
</div>

<%- @vMostrarBorrar = true %>

<%= render 'form' %>

app/views/rubros/index.html.erb
<div class="page-header">
  <h3><u>Todos los Rubros</u></h3>
</div>

<table id="form-new" class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>#</th>
      <th>Descripcion</th>
      <th>Suma?</th>
    </tr>
  </thead>
  <tbody>
    <% @rubros.each do |vRubro| %>
      <tr>
        <td> <%= vRubro.id %> </td>
        <td> <%= vRubro.rub_desc %> </td>
        <td> <%= if vRubro.rub_suma then "Si" else "No" end %> </td>
<!--        <td id="columna-mmb"><%= link_to 'Mostrar', vRubro %></td>
        <td id="columna-mmb"><%= link_to 'Borrar', vRubro, method: :delete, data: { confirm: 'Estas seguro que queres Borrar?' } %></td> -->
        <td id="columna-mmb"><%= link_to 'Modificar', edit_rubro_path(vRubro) %></td>
      </tr>
    <% end %>
  </tbody>
  
</table>

<%= link_to ' Nuevo Rubro ', new_rubro_path, class: "btn btn-primary" %>

app/views/rubros/new.html.erb
<div class="page-header">
  <h3><u>Nuevo Rubro</u></h3>
</div>


<%- @vMostrarBorrar = false %>

<%= render 'form' %>

app/views/rubros/show.html.erb
<div class="page-header">
  <h3><u>Rubro</u>: <%= @rubro.rub_desc %></h3>
</div>

  <% if @rubro.rub_suma %>
		<p> <strong>Suma?:  SI</strong></p>
  <% else %>
		<p> <strong>Suma?:  NO</strong></p>
  <% end %>

<div class="actions">
  <br><br>
  <%= link_to "Modificar", edit_rubro_path(@rubro),  :class => "btn btn-primary" %>
  <%= link_to 'Ir Atras', rubros_path, class: "btn btn-primary" %>
</div>