config/routes.rb
Rails.application.routes.draw do
  resources :queries

  devise_for :users, :controllers => { registrations: 'registrations' }

  get 'estadisticas/index'

  resources :movimientos

  resources :formapagos

  resources :tipomovs

  resources :tipogastos

  resources :subrubros

  resources :rubros

  root to: 'queries#index'

end

app/models/tipomov.rb
class Tipomov < ActiveRecord::Base
end

app/controllers/tipomovs_controller.rb
class TipomovsController < ApplicationController
  before_action :set_tipomov, only: [:show, :edit, :update, :destroy]

  # GET /tipomovs
  # GET /tipomovs.json
  def index
    @tipomovs = Tipomov.all
  end

  # GET /tipomovs/1
  # GET /tipomovs/1.json
  def show
  end

  # GET /tipomovs/new
  def new
    @tipomov = Tipomov.new
  end

  # GET /tipomovs/1/edit
  def edit
  end

  # POST /tipomovs
  # POST /tipomovs.json
  def create
    @tipomov = Tipomov.new(tipomov_params)

    respond_to do |format|
      if @tipomov.save
        format.html { redirect_to @tipomov, notice: 'Se creo correctamente el Tipo de movimiento.' }
        format.json { render :show, status: :created, location: @tipomov }
      else
        format.html { render :new }
        format.json { render json: @tipomov.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipomovs/1
  # PATCH/PUT /tipomovs/1.json
  def update
    respond_to do |format|
      if @tipomov.update(tipomov_params)
        format.html { redirect_to @tipomov, notice: 'Se actualizo correctamente el Tipo de movimiento.' }
        format.json { render :show, status: :ok, location: @tipomov }
      else
        format.html { render :edit }
        format.json { render json: @tipomov.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipomovs/1
  # DELETE /tipomovs/1.json
  def destroy
    @tipomov.destroy
    respond_to do |format|
      format.html { redirect_to tipomovs_url, notice: 'Se borro correctamente el Tipo de movimiento.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipomov
      @tipomov = Tipomov.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipomov_params
      params.require(:tipomov).permit(:tmo_desc)
    end
end

app/helpers/tipomovs_helper.rb
module TipomovsHelper
end

app/views/tipomovs/_form.html.erb
<%= form_for(@tipomov) do |f| %>
  <% if @tipomov.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipomov.errors.count, "error") %> prohibited this tipomov from being saved:</h2>

      <ul>
      <% @tipomov.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tmo_desc %><br>
    <%= f.text_field :tmo_desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipomovs/edit.html.erb
<h1>Editing tipomov</h1>

<%= render 'form' %>

<%= link_to 'Show', @tipomov %> |
<%= link_to 'Back', tipomovs_path %>

app/views/tipomovs/index.html.erb
<h1>Listing tipomovs</h1>

<table>
  <thead>
    <tr>
      <th>Tmo desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipomovs.each do |tipomov| %>
      <tr>
        <td><%= tipomov.tmo_desc %></td>
        <td><%= link_to 'Show', tipomov %></td>
        <td><%= link_to 'Edit', edit_tipomov_path(tipomov) %></td>
        <td><%= link_to 'Destroy', tipomov, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tipomov', new_tipomov_path %>

app/views/tipomovs/new.html.erb
<h1>New tipomov</h1>

<%= render 'form' %>

<%= link_to 'Back', tipomovs_path %>

app/views/tipomovs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tmo desc:</strong>
  <%= @tipomov.tmo_desc %>
</p>

<%= link_to 'Edit', edit_tipomov_path(@tipomov) %> |
<%= link_to 'Back', tipomovs_path %>