config/routes.rb
Rails.application.routes.draw do
  resources :queries

  devise_for :users, :controllers => { registrations: 'registrations' }

  get 'estadisticas/index'

  resources :movimientos

  resources :formapagos

  resources :tipomovs

  resources :tipogastos

  resources :subrubros

  resources :rubros

  root to: 'queries#index'

end

app/models/formapago.rb
class Formapago < ActiveRecord::Base
end

app/models/movimiento.rb
class Movimiento < ActiveRecord::Base
  belongs_to :subrubro
  belongs_to :tipogasto
  belongs_to :tipomov
  belongs_to :formapago
  belongs_to :user
end

app/models/query.rb
class Query < ActiveRecord::Base
  belongs_to :user
end

app/models/rubro.rb
class Rubro < ActiveRecord::Base
end

app/models/subrubro.rb
class Subrubro < ActiveRecord::Base
  belongs_to :rubro
end

app/models/tipogasto.rb
class Tipogasto < ActiveRecord::Base
end

app/models/tipomov.rb
class Tipomov < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def nombre_completo
  	nombre + " " + apellido
  end
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController

  respond_to :html, :js

  def index
    vPrimerdia = Date.today.year.to_s+Date.today.month.to_s+"01"
    @queryRU = Movimiento.joins(subrubro: :rubro).select("rub_desc, sum(mov_importe) importe").where("mov_fecha between ? and ?", vPrimerdia, Date.today).group("rubro_id")
    @querySR = Movimiento.joins(subrubro: :rubro).select("rub_desc, sru_desc, sum(mov_importe) importe").where("mov_fecha between ? and ?", vPrimerdia, Date.today).group("rubro_id, subrubro_id")
    @queryTG = Movimiento.joins(:tipogasto).select("tga_desc, sum(mov_importe) importe").where("mov_fecha between ? and ?", vPrimerdia, Date.today).group("tipogasto_id")
    @queryTM = Movimiento.joins(:tipomov).select("tmo_desc, sum(mov_importe) importe").where("mov_fecha between ? and ?", vPrimerdia, Date.today).group("tipomov_id")
  end

  def create
    @query = Query.create(query_params)
    @queryRU = Movimiento.joins(subrubro: :rubro).select("rub_desc, sum(mov_importe) importe").where("mov_fecha between ? and ?", @query.con_fechad, @query.con_fechah).group("rubro_id")
    @querySR = Movimiento.joins(subrubro: :rubro).select("rub_desc, sru_desc, sum(mov_importe) importe").where("mov_fecha between ? and ?", @query.con_fechad, @query.con_fechah).order("rubro_id, subrubro_id").group("rubro_id, subrubro_id")
    @queryTG = Movimiento.joins(:tipogasto).select("tga_desc, sum(mov_importe) importe").where("mov_fecha between ? and ?", @query.con_fechad, @query.con_fechah).group("tipogasto_id")
    @queryTM = Movimiento.joins(:tipomov).select("tmo_desc, sum(mov_importe) importe").where("mov_fecha between ? and ?", @query.con_fechad, @query.con_fechah).group("tipomov_id")
  end

  def new
    @query = Query.new
  end

  def update
    @query.update_attributes(task_params)
  end

  def destroy
    @query.destroy
  end

  private

    def all_tasks
      @queries = Query.all
    end

    def set_query
      @query = Query.find(params[:id])
    end

    def query_params
      params.require(:query).permit(:con_fechad, :con_fechah, :con_descripcion, :user_id)
    end
end

app/controllers/rubros_controller.rb
class RubrosController < ApplicationController
  before_action :set_rubro, only: [:show, :edit, :update, :destroy]

  # GET /rubros
  # GET /rubros.json
  def index
    @rubros = Rubro.all
  end

  # GET /rubros/1
  # GET /rubros/1.json
  def show
  end

  # GET /rubros/new
  def new
    @rubro = Rubro.new
  end

  # GET /rubros/1/edit
  def edit
  end

  # POST /rubros
  # POST /rubros.json
  def create
    @rubro = Rubro.new(rubro_params)

    respond_to do |format|
      if @rubro.save
        format.html { redirect_to @rubro, notice: 'Se creo correctamente el Rubro.' }
        format.json { render :show, status: :created, location: @rubro }
      else
        format.html { render :new }
        format.json { render json: @rubro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rubros/1
  # PATCH/PUT /rubros/1.json
  def update
    respond_to do |format|
      if @rubro.update(rubro_params)
        format.html { redirect_to @rubro, notice: 'Se actualizo correctamente el Rubro.' }
        format.json { render :show, status: :ok, location: @rubro }
      else
        format.html { render :edit }
        format.json { render json: @rubro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rubros/1
  # DELETE /rubros/1.json
  def destroy
    @rubro.destroy
    respond_to do |format|
      format.html { redirect_to rubros_url, notice: 'Se borro correctamente el Rubro.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rubro
      @rubro = Rubro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rubro_params
      params.require(:rubro).permit(:rub_desc, :rub_suma)
    end
end

app/controllers/tipomovs_controller.rb
class TipomovsController < ApplicationController
  before_action :set_tipomov, only: [:show, :edit, :update, :destroy]

  # GET /tipomovs
  # GET /tipomovs.json
  def index
    @tipomovs = Tipomov.all
  end

  # GET /tipomovs/1
  # GET /tipomovs/1.json
  def show
  end

  # GET /tipomovs/new
  def new
    @tipomov = Tipomov.new
  end

  # GET /tipomovs/1/edit
  def edit
  end

  # POST /tipomovs
  # POST /tipomovs.json
  def create
    @tipomov = Tipomov.new(tipomov_params)

    respond_to do |format|
      if @tipomov.save
        format.html { redirect_to @tipomov, notice: 'Se creo correctamente el Tipo de movimiento.' }
        format.json { render :show, status: :created, location: @tipomov }
      else
        format.html { render :new }
        format.json { render json: @tipomov.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipomovs/1
  # PATCH/PUT /tipomovs/1.json
  def update
    respond_to do |format|
      if @tipomov.update(tipomov_params)
        format.html { redirect_to @tipomov, notice: 'Se actualizo correctamente el Tipo de movimiento.' }
        format.json { render :show, status: :ok, location: @tipomov }
      else
        format.html { render :edit }
        format.json { render json: @tipomov.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipomovs/1
  # DELETE /tipomovs/1.json
  def destroy
    @tipomov.destroy
    respond_to do |format|
      format.html { redirect_to tipomovs_url, notice: 'Se borro correctamente el Tipo de movimiento.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipomov
      @tipomov = Tipomov.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipomov_params
      params.require(:tipomov).permit(:tmo_desc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estadisticas_helper.rb
module EstadisticasHelper
end

app/helpers/formapagos_helper.rb
module FormapagosHelper
end

app/helpers/movimientos_helper.rb
module MovimientosHelper
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/helpers/rubros_helper.rb
module RubrosHelper
end

app/helpers/subrubros_helper.rb
module SubrubrosHelper
end

app/helpers/tipogastos_helper.rb
module TipogastosHelper
end

app/helpers/tipomovs_helper.rb
module TipomovsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gastos</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div id="Contenedor-menu-interno" class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">eGastos</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
    			<li><%= link_to "Estadisticas", queries_path %> </li>
          <li><%= link_to "Movimientos", movimientos_path %> </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Tablas<span class="caret"></span></a>
            <ul class="dropdown-menu dropdown-inverse" role="menu">
              <li><%= link_to "Rubros", rubros_path %> </li>
              <li><%= link_to "SubRubros", subrubros_path %> </li>
              <li class="divider"></li>
              <li><%= link_to "TipoGasto", tipogastos_path %> </li>
              <li><%= link_to "TipoMov", tipomovs_path %> </li>
              <li><%= link_to "FormaPago", formapagos_path %> </li>
        <%end%>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
          <li><%= link_to current_user.nombre_completo, edit_user_registration_path %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <%else%>
          <li><%= link_to "Registrarse", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <%end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div id="Contenedor-general" class="container"> 
    <div class="alert alert-info" role="alert" style="margin-top: 20px;width: 572px;">
        <p>Mensaje del Sistema: <%= notice %></p>
<!--      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>    -->
    </div>

		<%= yield %>
		<br><br>
</div>

</body>

</html>